[INFO][2021/11/04 09:49:10][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/04 09:49:33][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/services/place.py changed, reloading.
[INFO][2021/11/04 09:49:34][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/04 09:49:36][django.server - log_message] - 161: "GET /getphonenumber?address=%22Nh%C3%A0%20th%E1%BB%9D%20%C4%90%E1%BB%A9c%20B%C3%A0%22 HTTP/1.1" 200 5605
[INFO][2021/11/04 09:49:45][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/services/place.py changed, reloading.
[INFO][2021/11/04 09:49:45][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/04 09:49:50][django.server - log_message] - 161: "GET /getphonenumber?address=%22Nh%C3%A0%20th%E1%BB%9D%20%C4%90%E1%BB%A9c%20B%C3%A0%22 HTTP/1.1" 200 5605
[INFO][2021/11/04 09:52:00][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/services/place.py changed, reloading.
[INFO][2021/11/04 09:52:01][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/04 09:52:04][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/services/place.py changed, reloading.
[INFO][2021/11/04 09:52:04][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/04 09:52:20][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/phone_number_tracer/api.py changed, reloading.
[INFO][2021/11/04 09:52:21][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/04 09:52:22][django.server - log_message] - 161: "GET /getphonenumber?address=%22Nh%C3%A0%20th%E1%BB%9D%20%C4%90%E1%BB%A9c%20B%C3%A0%22 HTTP/1.1" 200 5656
[INFO][2021/11/04 09:52:41][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/services/place.py changed, reloading.
[INFO][2021/11/04 09:52:41][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/04 10:03:30][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/services/place.py changed, reloading.
[INFO][2021/11/04 10:03:30][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/04 10:03:46][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/services/place.py changed, reloading.
[INFO][2021/11/04 10:03:47][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/04 10:06:01][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/services/place.py changed, reloading.
[INFO][2021/11/04 10:06:02][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/04 10:06:17][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/services/place.py changed, reloading.
[INFO][2021/11/04 10:06:17][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/04 10:07:35][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/phone_number_tracer/api.py changed, reloading.
[INFO][2021/11/04 10:07:36][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/04 10:07:52][django.server - log_message] - 161: "GET /getphonenumber?address=%22Nh%C3%A0%20th%E1%BB%9D%20%C4%90%E1%BB%A9c%20B%C3%A0%22 HTTP/1.1" 200 5986
[INFO][2021/11/04 10:07:52][django.server - log_message] - 161: "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[INFO][2021/11/04 10:07:52][django.server - log_message] - 161: "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[INFO][2021/11/04 10:07:52][django.server - log_message] - 161: "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[INFO][2021/11/06 01:15:25][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/06 02:38:28][django.server - log_message] - 161: "GET /getphonenumber?address=%22Nh%C3%A0%20th%E1%BB%9D%20%C4%90%E1%BB%A9c%20B%C3%A0%22 HTTP/1.1" 200 5986
[INFO][2021/11/06 02:38:28][django.server - log_message] - 161: "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[INFO][2021/11/06 02:38:28][django.server - log_message] - 161: "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[INFO][2021/11/06 02:38:28][django.server - log_message] - 161: "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[INFO][2021/11/06 03:17:16][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/services/place.py changed, reloading.
[INFO][2021/11/06 03:17:17][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[WARNING][2021/11/06 03:20:12][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 03:20:49][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 03:21:50][django.request - log_response] - 224: Bad Request: /getphonenumber
[INFO][2021/11/06 03:30:05][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/phone_number_tracer/api.py changed, reloading.
[INFO][2021/11/06 03:30:06][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/06 03:31:05][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/services/place.py changed, reloading.
[INFO][2021/11/06 03:31:06][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/06 03:31:18][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/phone_number_tracer/api.py changed, reloading.
[INFO][2021/11/06 03:31:19][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[WARNING][2021/11/06 05:02:16][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:06:44][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:07:18][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:11:40][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:14:26][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:14:54][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:15:35][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:15:44][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:16:52][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:18:34][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:19:02][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:20:01][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:20:42][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:21:05][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:40:56][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:41:21][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 05:43:06][django.request - log_response] - 224: Bad Request: /getphonenumber
[INFO][2021/11/06 05:43:52][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/phone_number_tracer/api.py changed, reloading.
[INFO][2021/11/06 05:43:53][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[WARNING][2021/11/06 05:43:56][django.request - log_response] - 224: Bad Request: /getphonenumber
[INFO][2021/11/06 05:45:18][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/phone_number_tracer/api.py changed, reloading.
[INFO][2021/11/06 05:45:19][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[ERROR][2021/11/06 05:45:20][django.request - log_response] - 224: Internal Server Error: /getphonenumber
Traceback (most recent call last):
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[ERROR][2021/11/06 05:46:48][django.request - log_response] - 224: Internal Server Error: /getphonenumber
Traceback (most recent call last):
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[ERROR][2021/11/06 05:49:05][django.request - log_response] - 224: Internal Server Error: /getphonenumber
Traceback (most recent call last):
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[INFO][2021/11/06 07:42:25][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[ERROR][2021/11/06 07:42:51][django.request - log_response] - 224: Internal Server Error: /getphonenumber
Traceback (most recent call last):
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[INFO][2021/11/06 07:44:01][django.utils.autoreload - trigger_reload] - 251: /Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/phone_number_tracer/api.py changed, reloading.
[INFO][2021/11/06 07:44:01][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[ERROR][2021/11/06 07:44:03][django.request - log_response] - 224: Internal Server Error: /getphonenumber
Traceback (most recent call last):
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[ERROR][2021/11/06 07:56:39][django.request - log_response] - 224: Internal Server Error: /getphonenumber
Traceback (most recent call last):
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[ERROR][2021/11/06 07:57:12][django.request - log_response] - 224: Internal Server Error: /getphonenumber
Traceback (most recent call last):
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/simple_phone_number_tracer/phone_number_tracer/api.py", line 37, in get
    {"error": f"{e}"},
UnboundLocalError: local variable 'e' referenced before assignment
[ERROR][2021/11/06 07:57:38][django.request - log_response] - 224: Internal Server Error: /getphonenumber
Traceback (most recent call last):
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/hungnk2/Works/Projects/backend/funnelbeam_venv/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[WARNING][2021/11/06 07:57:47][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 07:58:07][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 07:58:44][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 07:59:00][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 07:59:08][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:01:13][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:01:13][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:01:39][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:01:39][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:03:18][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:03:18][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:03:38][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:03:38][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:03:59][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:03:59][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:03:59][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:05:39][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:05:39][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:05:39][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:07:13][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:07:13][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:07:13][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:12:09][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:12:09][django.request - log_response] - 224: Bad Request: /getphonenumber
[WARNING][2021/11/06 08:12:09][django.request - log_response] - 224: Bad Request: /getphonenumber
[INFO][2021/11/06 08:30:55][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/06 08:34:58][django.utils.autoreload - run_with_reloader] - 637: Watching for file changes with StatReloader
[INFO][2021/11/06 08:35:01][django.server - log_message] - 161: "GET /getphonenumber?address=Computer%20History%20Museum%20Mountain%20View%20USA HTTP/1.1" 200 5914
[INFO][2021/11/06 08:35:01][django.server - log_message] - 161: "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[INFO][2021/11/06 08:35:01][django.server - log_message] - 161: "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[INFO][2021/11/06 08:35:01][django.server - log_message] - 161: "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
